export const colors = {
  primary: "#57afcb",
  primaryDark: "#468ea4",
  primaryLight: "#afcad2",
  primaryText: "#212121",
  secondaryText: "#757575",
  filledText: "#ffffff",
  divider: "#BDBDBD",
  disabled: "#DDDDDD",
  background: "#f3f9fb",
  primarySurface: "#f8fbfd",
  secondarySurface: "#ffffff",
  error: "#C03403",
  errorBackground: "#F2D6CD",
  warning: "#FFBB50",
  warningBackground: "#FFEED4",
  transparent: "rgba(0, 0, 0, 0)",
  overlay: "rgba(0, 0, 0, 0.2)",
  shadow: "#000000",
}
