export const colors = {
  primary: '#57afcb',
  primaryDark: '#468ea4',
  primaryLight: '#afcad2',
  primaryText: '#212121',
  secondaryText: '#757575',
  filledText: '#ffffff',
  border: '#bdbdbd',
  disabled: '#dddddd',
  background: '#f3f9fb',
  primarySurface: '#f8fbfd',
  secondarySurface: '#ffffff',
  success: '#4bb543',
  error: '#c03403',
  errorBackground: '#f2d6cd',
  warning: '#ffbb50',
  warningBackground: '#ffeed4',
  transparent: 'rgba(0, 0, 0, 0)',
  overlay: 'rgba(0, 0, 0, 0.2)',
  shadow: '#000000',
};
